config/routes.rb
Rails.application.routes.draw do
  get 'admin' => "admin#index"
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  resources :products

  root 'store#index' , as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id, number)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += number
      if current_item.quantity < 0
        current_item.quantity =0
      end
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def reduce_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity -= 1
      if current_item.quantity < 0
        current_item.quantity =0
      end
    end
    current_item
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to store_url, notice: 'Invalid cart'
  end

  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
- if !@cart.line_items.empty?
  %h3= link_to "Cart", cart_path(@cart)
  %table.table.table-striped
    %thead
      %tr
        %th Product
        %th Number
        -if @sidebar != 1
          %th
        %th Total
        -if @sidebar != 1
          %th=t '.actions', :default => t("helpers.actions")
    %tbody
      = render(cart.line_items)

      %tr.total_line
        -if @sidebar != 1
          %td.total_text{:colspan => "3"} Total:
        -else
          %td.total_text{:colspan => "2"} Total:
        %td.total_cell= number_to_currency(cart.total_price)

  -if @sidebar != 1
    = link_to t('.back', :default => t("helpers.links.back")), store_path, :class => 'btn btn-default'
  = button_to 'Check out', new_order_path, method: :get, :class => "btn btn-success"
  -if @sidebar != 1
    = button_to 'Empty cart', cart, method: :delete, data: {confirm: 'Are you sure?'} , :class => 'btn btn-danger'

app/views/carts/_cart_mini.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Product
      %th Number
      %th Total
  %tbody
    - @cart.line_items.each do |item|
      %tr
        %td= item.product.title
        %td= item.quantity
        %td.item_price= number_to_currency(item.total_price)

    %tr.total_line
      %td.total_text{:colspan => "2"} Total:
      %td.total_cell= number_to_currency(@cart.total_price)

= button_to 'Empty cart', @cart, method: :delete, data: {confirm: 'Are you sure?'} , :class => 'btn btn-danger'

app/views/carts/_form.html.haml
= form_for @cart, html: { class: "form form-horizontal cart" } do |f|
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), carts_path, :class => 'btn btn-default'

app/views/carts/edit.html.haml
- model_class = Cart
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/carts/index.html.haml
- model_class = Cart
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to cart.id, cart_path(cart)
        %td=l cart.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_cart_path(cart), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), cart_path(cart), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_cart_path, :class => 'btn btn-primary'

app/views/carts/new.html.haml
- model_class = Cart
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/carts/show.html.haml
- model_class = Cart

.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

= render(@cart)